# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatchPracticleTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatchPracticleTestDemo
pod 'Moya'

  target 'CatchPracticleTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatchPracticleTestDemoUITests' do
    # Pods for testing
  end

end
